/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HowOldIsClaudeRouteImport } from './routes/how-old-is-claude'
import { Route as HolidayProtocolRouteImport } from './routes/holiday-protocol'
import { Route as FavoriteThingsRouteImport } from './routes/favorite-things'
import { Route as AboutClaudeRouteImport } from './routes/about-claude'
import { Route as IndexRouteImport } from './routes/index'

const HowOldIsClaudeRoute = HowOldIsClaudeRouteImport.update({
  id: '/how-old-is-claude',
  path: '/how-old-is-claude',
  getParentRoute: () => rootRouteImport,
} as any)
const HolidayProtocolRoute = HolidayProtocolRouteImport.update({
  id: '/holiday-protocol',
  path: '/holiday-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteThingsRoute = FavoriteThingsRouteImport.update({
  id: '/favorite-things',
  path: '/favorite-things',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutClaudeRoute = AboutClaudeRouteImport.update({
  id: '/about-claude',
  path: '/about-claude',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-claude': typeof AboutClaudeRoute
  '/favorite-things': typeof FavoriteThingsRoute
  '/holiday-protocol': typeof HolidayProtocolRoute
  '/how-old-is-claude': typeof HowOldIsClaudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-claude': typeof AboutClaudeRoute
  '/favorite-things': typeof FavoriteThingsRoute
  '/holiday-protocol': typeof HolidayProtocolRoute
  '/how-old-is-claude': typeof HowOldIsClaudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-claude': typeof AboutClaudeRoute
  '/favorite-things': typeof FavoriteThingsRoute
  '/holiday-protocol': typeof HolidayProtocolRoute
  '/how-old-is-claude': typeof HowOldIsClaudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-claude'
    | '/favorite-things'
    | '/holiday-protocol'
    | '/how-old-is-claude'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-claude'
    | '/favorite-things'
    | '/holiday-protocol'
    | '/how-old-is-claude'
  id:
    | '__root__'
    | '/'
    | '/about-claude'
    | '/favorite-things'
    | '/holiday-protocol'
    | '/how-old-is-claude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutClaudeRoute: typeof AboutClaudeRoute
  FavoriteThingsRoute: typeof FavoriteThingsRoute
  HolidayProtocolRoute: typeof HolidayProtocolRoute
  HowOldIsClaudeRoute: typeof HowOldIsClaudeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/how-old-is-claude': {
      id: '/how-old-is-claude'
      path: '/how-old-is-claude'
      fullPath: '/how-old-is-claude'
      preLoaderRoute: typeof HowOldIsClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holiday-protocol': {
      id: '/holiday-protocol'
      path: '/holiday-protocol'
      fullPath: '/holiday-protocol'
      preLoaderRoute: typeof HolidayProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite-things': {
      id: '/favorite-things'
      path: '/favorite-things'
      fullPath: '/favorite-things'
      preLoaderRoute: typeof FavoriteThingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-claude': {
      id: '/about-claude'
      path: '/about-claude'
      fullPath: '/about-claude'
      preLoaderRoute: typeof AboutClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutClaudeRoute: AboutClaudeRoute,
  FavoriteThingsRoute: FavoriteThingsRoute,
  HolidayProtocolRoute: HolidayProtocolRoute,
  HowOldIsClaudeRoute: HowOldIsClaudeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
